config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    get "switch_language/:locale", to: "application#switch_language", as: :switch_language
    resources :jobs
    resources :companies
    resources :users do
      resources :user_profiles do
        member do
          delete :remove_skill
          post :add_skill
        end
      end
      resources :user_projects
      resources :user_social_links
    end
    resources :applications, only: %i(create show update)
    resources :notifications, only: [] do
      member do
        patch :mark_as_read
      end
      collection do
        patch :mark_all_as_read
      end
    end

    get "home/index"
    root "home#index"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    namespace :enterprise do
      get "/login", to: "sessions#new"
      post "/login", to: "sessions#create"
      get "/logout", to: "sessions#destroy"
      root "dashboard#index"
      resources :jobs
      resources :applications do
        member do
          patch :update_status
        end
        resources :interview_processes, only: %i(create update destroy)
      end
    end

    namespace :admin do
      get "/login", to: "sessions#new"
      post "/login", to: "sessions#create"
      get "/logout", to: "sessions#destroy"
      root "dashboard#index"
      resources :jobs, only: %i(update)
    end
  end
end

app/models/job.rb
class Job < ApplicationRecord
  PERMITTED_PARAMS = [
    :title,
    :description,
    :experience_level,
    :work_type,
    :salary_range,
    :location,
    :status,
    {required_skills: [:key, :value]}
  ].freeze

  acts_as_paranoid
  belongs_to :company
  has_many :applications, dependent: :destroy
  has_many :applicants, through: :applications, source: :user

  enum work_type: {Remote: 0, Office: 1, Hybrid: 2, Oversea: 3}
  enum status: {draft: 0, pending: 1, active: 2, closed: 3}

  scope :filter_by_work_type, lambda {|work_types|
    where(work_type: work_types) if work_types.present?
  }

  scope :filter_by_location, lambda {|locations|
    return if locations.blank?

    target_locations = Settings.jobs.filter_locations
    locations = Array(locations)

    if locations.include?("others")
      if locations.size == 1
        where.not(location: target_locations)
      else
        where.not(location: target_locations - locations)
      end
    else
      where(location: locations)
    end
  }

  scope :search_by_keyword, lambda {|keyword|
    return if keyword.blank?

    where(
      "LOWER(jobs.title) LIKE :keyword OR " \
      "LOWER(jobs.description) LIKE :keyword OR " \
      "LOWER(companies.name) LIKE :keyword",
      keyword: "%#{keyword.downcase}%"
    ).joins(:company)
  }

  scope :related_jobs, lambda {|job|
    where.not(id: job.id)
         .where(company_id: job.company_id)
         .limit(Settings.jobs.related_jobs_size)
  }

  scope :pending, ->{where(status: :pending)}
  scope :active, ->{where(status: :active)}
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  def update
    @job = Job.find(params[:id])
    if @job.update(status: params[:status])
      flash[:success] = t "flash.jobs.update_success"
      redirect_to admin_root_path
    else
      render "admin/dashboard/index"
    end
  end
end

app/controllers/enterprise/jobs_controller.rb
class Enterprise::JobsController < ApplicationController
  layout "enterprise"
  before_action :load_job, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = current_user.company.jobs.with_deleted.order(created_at: :desc)
  end

  def new
    @job = current_user.company.jobs.new
  end

  def create
    update_params = job_params.merge(required_skills: transform_skills)
    @job = current_user.company.jobs.new(update_params)
    if @job.save
      flash[:success] = t "flash.jobs.save_success"
      redirect_to enterprise_jobs_path
    else
      flash.now[:danger] = t "flash.jobs.save_error"
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    update_params = job_params.merge(required_skills: transform_skills)
    if @job.update(update_params)
      flash[:success] = t "flash.jobs.update_success"
      redirect_to enterprise_job_path(id: @job.id)
    else
      flash.now[:danger] = t "flash.jobs.update_error"
      render :edit
    end
  end

  def destroy
    @job.destroy
    flash[:success] = t "flash.jobs.delete_success"
    redirect_to enterprise_jobs_path
  end

  private

  def load_job
    @job = current_user.company.jobs.with_deleted.find(params[:id])
  end

  def job_params
    params.require(:job).permit(Job::PERMITTED_PARAMS)
  end

  def transform_skills
    params[:job][:required_skills]&.map do |skill|
      [skill[:key], skill[:value]]
    end.to_h || {}
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    jobs = Job
           .filter_by_work_type(params[:work_type])
           .search_by_keyword(params[:keyword])
           .filter_by_location(params[:location])
           .active

    @pagy, @jobs = pagy(jobs, limit: Settings.jobs.page_size)
  end

  def show
    @job = Job.find_by id: params[:id]

    if @job.nil?
      flash[:danger] = t "jobs.job_not_found"
      redirect_to root_path
    else
      @related_jobs = Job.related_jobs(@job)
    end
  end
end

app/helpers/enterprise/job_helper.rb
module Enterprise::JobHelper
  def work_type_options
    Job.work_types.keys.map{|key| [key.humanize, key]}
  end

  def status_options
    Job.statuses.keys.map{|key| [key.humanize, key]}
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def work_types
    [
      {key: "jobs.filter.remote", value: "0"},
      {key: "jobs.filter.office", value: "1"},
      {key: "jobs.filter.hybrid", value: "2"},
      {key: "jobs.filter.overseas", value: "3"}
    ]
  end

  def locations
    [
      {key: "jobs.filter.hanoi", value: "Hà Nội"},
      {key: "jobs.filter.danang", value: "Đà Nẵng"},
      {key: "jobs.filter.hcm", value: "Hồ Chí Minh"},
      {key: "jobs.filter.others", value: "others"}
    ]
  end
end

app/views/jobs/_apply_modal.html.erb
<div class="modal fade" id="applyJobModal-<%= job.id %>" tabindex="-1" aria-labelledby="applyJobModalLabel-<%= job.id %>" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <%= form_with model: @application, id: "jobApplicationForm-#{job.id}", url: applications_path, method: :post, local: true do |f| %>
        <%= f.hidden_field :job_id, value: job.id %>
        <div class="modal-header">
          <h5 class="modal-title text-center w-100" id="applyJobLabelModal-<%= job.id %>"><%= t "user.apply.apply_for", job: job.title %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="progress mb-4" style="height: 20px;">
            <div id="progressBar-<%= job.id %>" class="progress-bar fw-bold" role="progressbar" style="width: 50%;" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">
              Step 1 of 2
            </div>
          </div>

          <div id="step1" class="step">
            <div class="w-100 fs-5 fw-bold text-center"><%= t "user.apply.confirm_info" %></div> 
            <div class="mb-3 d-flex flex-column">
              <div class="d-flex justify-content-between align-items-center">
                <span class="fs-5 fw-bold"><%= t "user.apply.job_confirm" %></span>
                <%= link_to  t("user.apply.job_link"), job_path(id: job.id), class: "btn btn-outline-primary mt-2" %>
              </div>
              <span><strong><%= t "user.apply.job_title" %></strong> <%= job.title %></span>
              <span><strong><%= t "user.apply.company" %></strong> <%= job.company.name %></span>
              <span><strong><%= t "user.apply.location" %></strong> <%= job.location %></span>
              <span><strong><%= t "user.apply.work_type" %></strong> <%= job.work_type %></span>
              <span><strong><%= t "user.apply.salary" %></strong> <%= job.salary_range %></span>
            </div>

            <div class="mb-3 d-flex flex-column">
              <div class="d-flex justify-content-between align-items-center">
                <span class="fs-5 fw-bold"><%= t "user.apply.contact" %></span>
                <%= link_to t("user.apply.edit_profile_link"), user_path(id: current_user.id), class: "btn btn-outline-primary mt-2" %>
              </div>
              <span><strong><%= t "user.apply.name" %></strong> <%= current_user.full_name %></span>
              <span><strong><%= t "user.apply.email" %></strong> <%= current_user.email %></span>
              <span><strong><%= t "user.apply.phone" %></strong> <%= current_user.phone %></span>
            </div>
          </div>

          <div id="step2" class="step d-none">
            <div class="w-100 fs-5 text-center fw-bold"><%= t "user.apply.upload_cv" %></div> 
            <% if current_user.user_profile && current_user.user_profile.cv_file.attached? %>
              <div class="d-flex justify-content-between align-items-center">
                <p>
                  <i class="fas fa-file-pdf"></i> <%= t "user.profile.current_cv" %>
                  <%= link_to t("user.profile.download_cv"), rails_blob_path(current_user.user_profile.cv_file, disposition: "attachment"), target: "_blank" %>
                </p>
                <div class="form-check">
                  <%= f.label :use_existing_cv, t("user.apply.use_current_cv"), class: "form-check-label" %>
                  <%= f.check_box :use_existing_cv, { class: "form-check-input", id: "useExistingCV-#{job.id}" }, true, false %>
                </div>
              </div>
            <% else %>
              <p><%= t "user.apply.no_cv" %></p>
            <% end %>
              <div class="form-group">
                <i class="fas fa-file-pdf"></i>
                <%= f.label :cv_file, t("user.profile.upload_cv") %>
                <%= f.file_field :cv_file, class: "form-control mt-1" %>
              </div>
          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><%= t "user.modal.cancel" %></button>
          <button type="button" class="btn btn-outline-primary" id="nextStep-<%= job.id %>"><%= t "user.modal.next" %></button>
          <button type="submit" form="jobApplicationForm-<%= job.id %>" class="btn btn-secondary d-none" id="submitApplication-<%= job.id %>" disabled><%= t "user.modal.submit" %></button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/_job.html.erb
<div class="col">
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title"><%= job.title %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= job.company.name %></h6>
      <div class="d-flex justify-content-between align-items-center">
        <small class="text-muted mr-2"><%= job.location %></small>
        <small class="text-muted mr-2"><%= job.work_type %></small>
      </div>
      <p class="card-text"><%= job.description.truncate(Settings.jobs.description_max_length) %></p>
      <div class="d-flex justify-content-between align-items-center">
        <p><strong><%= job.salary_range %></strong></p>
        <small class="text-muted"><%= time_ago_in_words(job.created_at) %></small>
      </div>
      <div class="d-flex justify-content-between align-items-center">
        <%= link_to t("jobs.view_details"), job_path(id: job.id), class: "btn btn-outline-primary" %>
        <% if current_user %>
          <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#applyJobModal-<%= job.id %>">
            <%= t "jobs.apply_now" %>
          </button>
          <%= render partial: "apply_modal", locals: {job: job} %>
        <% else %>
          <% store_location %>
          <%= link_to t("jobs.apply_now"), login_path, class: "btn btn-outline-primary" %>
        <% end %> 
      </div>
    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="container my-4">
  <div class="row">
    <div class="col-md-3">
      <div class="d-flex justify-content-between align-items-center">
        <p class="h4 fw-bold" ><%= t "jobs.filters" %></p>
        <%= link_to t("jobs.reset"), jobs_path, class: "btn btn-outline-danger" %>
      </div>
      <div class="mb-3">
        <%= form_with url: jobs_path, method: :get, local: true do |f| %>
          <div class="search-bar my-4">
            <div class="text_field_wrap d-flex border border-secondary-subtle rounded-3 px-2 align-items-center">
              <i class="fa-solid fa-magnifying-glass"></i>
              <%= f.text_field :keyword, placeholder: t("home.hero.search_placeholder"), value: params[:keyword], class: "form-control w-100 me-2 border-0 outline-none" %>
            </div>
          </div>
          <p class="h5 fw-bold"><%= t "jobs.job_type" %></p>
          <% work_types.each do |type| %>
            <div class="d-flex justify-content-between align-items-center mt-2">
              <p class="mb-0 h5"><%= t type[:key] %></p>
              <%= check_box_tag "work_type[]", type[:value], params[:work_type]&.include?(type[:value]) %>
            </div>
          <% end %>   
          
          <p class="h5 fw-bold mt-3"><%= t "jobs.location" %></p>
          <% locations.each do |location| %>
            <div class="d-flex justify-content-between align-items-center mt-2">
              <p class="mb-0 h5"><%= t location[:key] %></p>
              <%= check_box_tag "location[]", location[:value], params[:location]&.include?(location[:value]) %>
            </div>
          <% end %>
          <%= f.submit t("jobs.apply"), class: "btn btn-primary mt-3 float-end" %>
        <% end %>               
      </div>
    </div>

    <div class="col-md-9">
      <% if params[:keyword].present? %>
        <h5 class="fw-bold"><%= t "jobs.result_for_keyword" %> "<%= params[:keyword] %>"</h5>
      <% end %>
      <h5><%= t "jobs.show_result", count: @pagy.count %></h5>
      
      <div class="row row-cols-1 row-cols-md-2 g-4">
        <%= render @jobs %> 
      </div>

      <div class="mt-4 float-end">
        <%== pagy_bootstrap_nav @pagy %>
      </div>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="container mt-5 mb-5">
  <div class="row">
    <div class="col-lg-8">
      <div class="mb-4">
        <h1 class="display-5"><%= @job.title %></h1>
        <p class="text-muted">
          <%= @job.location %> • <%= @job.work_type %>
        </p>
        <p class="text-muted">
          <%= t "jobs.posted" %> <%= time_ago_in_words(@job.created_at) %> <%= t "ago" %> • <%= @job.applications.count %> <%= t "jobs.applications" %>
        </p>
      </div>
    </div>
    
    <div class="col-lg-4">
      <div class="row">
        <div class="col-sm-6 text-center">
          <div class="bg-light py-3 rounded-2">
            <i class="fa-regular fa-bookmark"></i> <%= t "jobs.save" %>
          </div>
        </div>
        <div class="col-sm-6 text-center">
          <div class="bg-light py-3 rounded-2">
            <i class="fa-solid fa-share"></i> <%= t "jobs.share" %>
          </div>
        </div>
        <div class="text-center mt-4">
          <% if current_user %>
            <button type="button" class="w-100 btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#applyJobModal-<%= @job.id %>">
              <%= t "jobs.apply_now" %>
            </button>
            <%= render partial: "apply_modal", locals: {job: @job} %>
          <% else %>
            <% store_location %>
            <%= link_to t("jobs.apply_now"), login_path, class: "w-100 btn btn-primary btn-lg" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="divider col-lg-12 mb-3"></div>

    <div class="col-lg-8">
      <div class="card mb-4 border-0">
        <div class="card-body">
          <div class="row">
            <div class="col-sm-4">
              <div class="bg-light py-4 px-4 rounded-3">
                <h6 class="text-muted"><%= t "jobs.company" %></h6>
                <p class="text-primary fw-bold fs-5"><%= @job.company.name %></p>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="bg-light py-4 px-4 rounded-3">
                <h6 class="text-muted"><%= t "jobs.experience" %></h6>
                <p class="text-primary fw-bold fs-5"><%= @job.experience_level %></p>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="bg-light py-4 px-4 rounded-3">
                <h6 class="text-muted"><%= t "jobs.salary" %></h6>
                <p class="text-primary fw-bold fs-5"><%= @job.salary_range %></p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="mb-4">
        <h2><%= t "jobs.description" %></h2>
        <p><%= @job.description %></p>
      </div>

      <div class="mb-4">
        <h2><%= t "jobs.requirements" %></h2>
        <ul>
          <% @job.required_skills.each do |key, value| %>
            <li><%= key.capitalize %>: <%= value %></li>
          <% end %>
        </ul>
      </div>

      <div class="text-center mt-4">
        <% if current_user %>
          <button type="button" class="w-100 btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#applyJobModal-<%= @job.id %>">
            <%= t "jobs.apply_now" %>
          </button>
          <%= render partial: "apply_modal", locals: {job: @job} %>
        <% else %>
          <% store_location %>
          <%= link_to t("jobs.apply_now"), login_path, class: "w-100 btn btn-primary btn-lg" %>
        <% end %>
      </div>
    </div>

    <div class="col-lg-4">
      <h3><%= t "jobs.related_jobs" %></h3>
      <ul class="list-group">
        <%= render partial: "jobs/job", collection: @related_jobs, as: :job %>
      </ul>
    </div>
  </div>
</div>