config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    get "switch_language/:locale", to: "application#switch_language", as: :switch_language
    resources :jobs
    resources :companies
    resources :users do
      resources :user_profiles do
        member do
          delete :remove_skill
          post :add_skill
        end
      end
      resources :user_projects
      resources :user_social_links
    end
    resources :applications, only: %i(create show update)
    resources :notifications, only: [] do
      member do
        patch :mark_as_read
      end
      collection do
        patch :mark_all_as_read
      end
    end

    get "home/index"
    root "home#index"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    namespace :enterprise do
      get "/login", to: "sessions#new"
      post "/login", to: "sessions#create"
      get "/logout", to: "sessions#destroy"
      root "dashboard#index"
      resources :jobs
      resources :applications do
        member do
          patch :update_status
        end
        resources :interview_processes, only: %i(create update destroy)
      end
    end

    namespace :admin do
      get "/login", to: "sessions#new"
      post "/login", to: "sessions#create"
      get "/logout", to: "sessions#destroy"
      root "dashboard#index"
      resources :jobs, only: %i(update)
    end
  end
end

app/views/shared/_notification.html.erb
<div class="dropdown notifications-dropdown">
  <button class="btn btn-primary float-end" data-bs-toggle="dropdown" aria-expanded="false">
    <i class="fa-solid fa-bell"></i>
    <span class="noti-unread"><%= unread_notifications %></span>
  </button>
  <ul class="dropdown-menu notifications-dropdown-menu">
    <li class="px-3 py-2 border-bottom border-dark position-sticky top-0 bg-light">
      <span class="fw-bold fs-5"><%= t("notifications.notifications") %></span>
    </li>
    <% if current_user.notifications.any? %>
      <% current_user.notifications.each do |notification| %>
        <li class="dropdown-item py-2 border-bottom border-secondary-subtle <%= seen_background_color(notification) %>">
          <div class="d-flex align-items-center w-100">
            <% unless notification.is_read %>
              <%= link_to mark_as_read_notification_path(id: notification.id), data: { turbo_method: :patch }, class: "text-decoration-none text-dark" do %>
                <i class="fa-solid fa-circle-check"></i>
              <% end %>
            <% end %>
            <div class="ms-2 d-flex justify-content-between align-items-center w-100">
              <span class="fw-bold fs-5"><%= notification.title %></span>
              <span class="text-muted"><%= notification.created_at.strftime("%d/%m/%Y %H:%M") %></span>
            </div>
          </div>
          <span class="text-muted noti-text"><%= notification.content %></span>
        </li>
      <% end %>
    <% else %>
      <li class="dropdown-item text-center py-2 border-bottom border-secondary-subtle">
        <span class="fs-5"><%= t("notifications.no_notification") %></span>
      </li>
    <% end %>
    <li class="dropdown-item py-2 text-center position-sticky bottom-0 bg-light">
      <%= link_to t("notifications.mark_all_as_read"), mark_all_as_read_notifications_path, data: { turbo_method: :patch }, class: "text-decoration-none text center text-dark" %>
    </li>
  </ul>
</div>