config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    get "switch_language/:locale", to: "application#switch_language", as: :switch_language
    resources :jobs
    resources :companies
    resources :users do
      resources :user_profiles do
        member do
          delete :remove_skill
          post :add_skill
        end
      end
      resources :user_projects
      resources :user_social_links
    end
    resources :applications, only: %i(create show update)
    resources :notifications, only: [] do
      member do
        patch :mark_as_read
      end
      collection do
        patch :mark_all_as_read
      end
    end

    get "home/index"
    root "home#index"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    namespace :enterprise do
      get "/login", to: "sessions#new"
      post "/login", to: "sessions#create"
      get "/logout", to: "sessions#destroy"
      root "dashboard#index"
      resources :jobs
      resources :applications do
        member do
          patch :update_status
        end
        resources :interview_processes, only: %i(create update destroy)
      end
    end

    namespace :admin do
      get "/login", to: "sessions#new"
      post "/login", to: "sessions#create"
      get "/logout", to: "sessions#destroy"
      root "dashboard#index"
      resources :jobs, only: %i(update)
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  has_one_attached :logo

  has_many :jobs, dependent: :destroy
  has_many :company_reviews, dependent: :destroy
  has_many :company_followers, dependent: :destroy
  has_many :followers, through: :company_followers, source: :user
  has_many :users, dependent: :nullify
  has_many :applications, through: :jobs

  # Validations
  validates :name, presence: true,
length: {maximum: Settings.company.name_max_length}
  validates :description,
            length: {maximum: Settings.company.description_max_length},
            allow_blank: true
  validates :website,
            format: {with: URI::DEFAULT_PARSER.make_regexp(%w(http https)),
                     message: I18n.t("errors.messages.invalid_url")},
            allow_blank: true
  validate :logo_format

  scope :search, lambda {|search|
                   where("name LIKE ?", "%#{search}%") if search.present?
                 }

  private

  def logo_format
    return unless logo.attached?

    check_logo_size
    check_logo_format
  end

  def check_logo_size
    return unless logo.blob.byte_size > Settings.image.max_size.megabytes

    errors.add(:logo, I18n.t("errors.messages.avatar_too_large"))
  end

  def check_logo_format
    acceptable_types = Settings.image.acceptable_types
    return if acceptable_types.include?(logo.blob.content_type)

    errors.add(:logo, I18n.t("errors.messages.invalid_avatar_format"))
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @pagy, @companies = pagy(
      Company.search(params[:query]),
      limit: Settings.company.page_size
    )

    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end
end

app/views/companies/_company.html.erb
<div class="col-md-4">
  <div class="card company-card mb-4 mx-1">
    <div class="card-body">
      <h5 class="card-title"><%= company.name %></h5>
      <p class="card-text"><%= truncate(company.description, length: Settings.company.truncate_description) %></p>
      <% company.jobs.limit(2).each do |job| %>
        <div class="d-flex flex-column px-2 py-2 border border-primary-subtle mb-2 rounded-3">
          <span class="fw-bold"><%= job.title %></span>
          <small class="text-muted"><%= job.location %> | <%= job.salary_range %></small>
        </div>
      <% end %>
      <%= link_to t("company.view_details"), company_path(id: company.id), class: "btn btn-outline-primary w-100" %>
    </div>
  </div>
</div>

app/views/companies/index.html.erb
<div class="container py-4">
  <h1 class="text-center mb-4"><%= t "company.title" %></h1>
  <p class="text-center mb-4"><%= t "company.subtitle" %></p>

  <div class="search-bar mb-4">
    <%= form_with url: companies_path, method: :get, local: true, class: "d-flex justify-content-center" do |form| %>
      <div class="text_field_wrap d-flex border border-secondary-subtle rounded-3 px-2 align-items-center">
        <i class="fa-solid fa-magnifying-glass"></i>
        <%= form.text_field :query, placeholder: t("company.search_placeholder"), class: "form-control w-100 me-2 border-0" %>
      </div>
      <%= form.submit t("company.search"), class: "btn btn-primary mx-2" %>
    <% end %>
  </div>

  <div class="row" id="company-list">
    <%= render @companies %>
  </div>

  <% if @companies.size == Settings.company.page_size %>
    <div class="text-center mt-4">
      <%= link_to t("company.view_more"), companies_path(page: @pagy.next), method: :get, remote: true, data: {turbo_stream: true}, class: "btn btn-primary", id: "load-more-btn" %>
    </div>
  <% end %>
</div>

app/views/companies/index.turbo_stream.erb
<%= turbo_stream.append "company-list" do %>
  <%= render partial: "companies/company", collection: @companies, as: :company %>
<% end %>

<% if @companies.size == Settings.company.page_size %>
  <%= turbo_stream.replace "load-more-btn" do %>
    <%= link_to "Xem thêm", companies_path(page: @pagy.next), method: :get, remote: true, data: {turbo_stream: true}, class: "btn btn-primary", id: "load-more-btn" %>
  <% end %>
<% else %>
  <%= turbo_stream.remove "load-more-btn" %>
<% end %>