config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    get "switch_language/:locale", to: "application#switch_language", as: :switch_language
    resources :jobs
    resources :companies
    resources :users do
      resources :user_profiles do
        member do
          delete :remove_skill
          post :add_skill
        end
      end
      resources :user_projects
      resources :user_social_links
    end
    resources :applications, only: %i(create show update)
    resources :notifications, only: [] do
      member do
        patch :mark_as_read
      end
      collection do
        patch :mark_all_as_read
      end
    end

    get "home/index"
    root "home#index"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    namespace :enterprise do
      get "/login", to: "sessions#new"
      post "/login", to: "sessions#create"
      get "/logout", to: "sessions#destroy"
      root "dashboard#index"
      resources :jobs
      resources :applications do
        member do
          patch :update_status
        end
        resources :interview_processes, only: %i(create update destroy)
      end
    end

    namespace :admin do
      get "/login", to: "sessions#new"
      post "/login", to: "sessions#create"
      get "/logout", to: "sessions#destroy"
      root "dashboard#index"
      resources :jobs, only: %i(update)
    end
  end
end

app/models/job.rb
class Job < ApplicationRecord
  PERMITTED_PARAMS = [
    :title,
    :description,
    :experience_level,
    :work_type,
    :salary_range,
    :location,
    :status,
    {required_skills: [:key, :value]}
  ].freeze

  acts_as_paranoid
  belongs_to :company
  has_many :applications, dependent: :destroy
  has_many :applicants, through: :applications, source: :user

  enum work_type: {Remote: 0, Office: 1, Hybrid: 2, Oversea: 3}
  enum status: {draft: 0, pending: 1, active: 2, closed: 3}

  scope :filter_by_work_type, lambda {|work_types|
    where(work_type: work_types) if work_types.present?
  }

  scope :filter_by_location, lambda {|locations|
    return if locations.blank?

    target_locations = Settings.jobs.filter_locations
    locations = Array(locations)

    if locations.include?("others")
      if locations.size == 1
        where.not(location: target_locations)
      else
        where.not(location: target_locations - locations)
      end
    else
      where(location: locations)
    end
  }

  scope :search_by_keyword, lambda {|keyword|
    return if keyword.blank?

    where(
      "LOWER(jobs.title) LIKE :keyword OR " \
      "LOWER(jobs.description) LIKE :keyword OR " \
      "LOWER(companies.name) LIKE :keyword",
      keyword: "%#{keyword.downcase}%"
    ).joins(:company)
  }

  scope :related_jobs, lambda {|job|
    where.not(id: job.id)
         .where(company_id: job.company_id)
         .limit(Settings.jobs.related_jobs_size)
  }

  scope :pending, ->{where(status: :pending)}
  scope :active, ->{where(status: :active)}
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  def update
    @job = Job.find(params[:id])
    if @job.update(status: params[:status])
      flash[:success] = t "flash.jobs.update_success"
      redirect_to admin_root_path
    else
      render "admin/dashboard/index"
    end
  end
end

app/controllers/enterprise/applications_controller.rb
class Enterprise::ApplicationsController < ApplicationController
  layout "enterprise"
  include NotificationsHelper
  before_action :load_application, only: [:show, :update_status]

  def index
    applications = current_user.company.applications.order(created_at: :desc)
    @pagy, @applications = pagy(applications, limit: Settings.apply.page_size)
  end

  def show
    @interview_process = InterviewProcess.new
  end

  def update_status
    if @application.update(status: params[:status])
      handle_update_success(@application, params[:status])
    else
      flash[:danger] = t("flash.application.update_error")
      render :show
    end
  end

  private

  def load_application
    @application = current_user.company.applications
                               .includes(:interview_processes)
                               .find_by(id: params[:id])
    return if @application.present?

    flash[:danger] = t "enterprise.applications.not_found"
    redirect_to enterprise_applications_path
  end

  def handle_update_success application, status
    create_notification_for_applicant(
      application,
      t("notifications.application_status_updated"),
      t("notifications.application_status_updated_content",
        job: application.job.title, status: status.capitalize)
    )
    flash[:success] = t("flash.application.update_success")
    redirect_to enterprise_application_path(application)
  end
end

app/controllers/enterprise/dashboard_controller.rb
class Enterprise::DashboardController < ApplicationController
  layout "enterprise"

  def index
    candidates = User.with_role(:user)
                     .search(params[:search])
                     .sort_by_param(params[:sort_by])
    @pagy, @candidates = pagy(candidates,
                              limit: Settings.enterprise_scout.page_size)
  end
end

app/controllers/enterprise/interview_processes_controller.rb
class Enterprise::InterviewProcessesController < ApplicationController
  include NotificationsHelper
  before_action :set_application

  def create
    @interview_process = @application.interview_processes
                                     .build(interview_process_params)
    if @interview_process.save
      create_notification_for_applicant(
        @application,
        t("notifications.interview_process_created"),
        t("notifications.interview_process_created_content",
          job: @application.job.title)
      )
      flash[:success] = t("flash.interview.create_success")
    else
      flash[:danger] = t("flash.interview.create_error")
    end
    redirect_to enterprise_application_path(id: @application.id)
  end

  def update
    @interview_process = @application.interview_processes.find(params[:id])
    if @interview_process.update(interview_process_params)
      handle_update_success @application
    else
      flash[:danger] = t("flash.interview.update_error")
    end
    redirect_to enterprise_application_path(id: @application.id)
  end

  def destroy
    @interview_process = @application.interview_processes.find(params[:id])
    if @interview_process.destroy
      create_notification_for_applicant(
        @application,
        t("notifications.interview_process_deleted"),
        t("notifications.interview_process_deleted_content",
          job: @application.job.title)
      )
      flash[:success] = t("flash.interview.delete_success")
    else
      flash[:danger] = t("flash.interview.delete_error")
    end
    redirect_to enterprise_application_path(id: @application.id)
  end

  private

  def set_application
    @application = current_user.company.applications
                               .find(params[:application_id])
  end

  def interview_process_params
    params.require(:interview_process).permit(
      :stage_number, :stage_type, :interview_time, :interview_location,
      :interview_type, :interviewer_name, :status, :feedback, :rating, :result
    )
  end

  def handle_update_success application
    create_notification_for_applicant(
      application,
      t("notifications.interview_process_updated"),
      t("notifications.interview_process_updated_content",
        job: application.job.title)
    )
    flash[:success] = t("flash.interview.update_success")
  end
end

app/controllers/enterprise/jobs_controller.rb
class Enterprise::JobsController < ApplicationController
  layout "enterprise"
  before_action :load_job, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = current_user.company.jobs.with_deleted.order(created_at: :desc)
  end

  def new
    @job = current_user.company.jobs.new
  end

  def create
    update_params = job_params.merge(required_skills: transform_skills)
    @job = current_user.company.jobs.new(update_params)
    if @job.save
      flash[:success] = t "flash.jobs.save_success"
      redirect_to enterprise_jobs_path
    else
      flash.now[:danger] = t "flash.jobs.save_error"
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    update_params = job_params.merge(required_skills: transform_skills)
    if @job.update(update_params)
      flash[:success] = t "flash.jobs.update_success"
      redirect_to enterprise_job_path(id: @job.id)
    else
      flash.now[:danger] = t "flash.jobs.update_error"
      render :edit
    end
  end

  def destroy
    @job.destroy
    flash[:success] = t "flash.jobs.delete_success"
    redirect_to enterprise_jobs_path
  end

  private

  def load_job
    @job = current_user.company.jobs.with_deleted.find(params[:id])
  end

  def job_params
    params.require(:job).permit(Job::PERMITTED_PARAMS)
  end

  def transform_skills
    params[:job][:required_skills]&.map do |skill|
      [skill[:key], skill[:value]]
    end.to_h || {}
  end
end

app/controllers/enterprise/sessions_controller.rb
class Enterprise::SessionsController < ApplicationController
  layout "auth"
  def new; end

  def create
    user = User.find_by(email: params[:email], role: Settings.roles.enterprise)
    if user&.authenticate(params[:password])
      handle_successful_login(user)
    else
      handle_failed_login
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end

  def handle_successful_login user
    reset_session
    log_in user
    flash[:success] = t "flash.login.success"
    redirect_to enterprise_root_path
  end

  def handle_failed_login
    flash.now[:danger] = t "flash.login.error"
    render :new, status: :unprocessable_entity
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    jobs = Job
           .filter_by_work_type(params[:work_type])
           .search_by_keyword(params[:keyword])
           .filter_by_location(params[:location])
           .active

    @pagy, @jobs = pagy(jobs, limit: Settings.jobs.page_size)
  end

  def show
    @job = Job.find_by id: params[:id]

    if @job.nil?
      flash[:danger] = t "jobs.job_not_found"
      redirect_to root_path
    else
      @related_jobs = Job.related_jobs(@job)
    end
  end
end

app/helpers/enterprise/applications_helper.rb
module Enterprise::ApplicationsHelper
  def bootstrap_status_class status
    case status.to_s
    when "pending" then "bg-warning text-dark"
    when "canceled" then "bg-secondary"
    when "reviewing" then "bg-info"
    when "interviewing" then "bg-primary"
    when "accepted" then "bg-success"
    when "rejected" then "bg-danger"
    else "bg-light text-dark"
    end
  end

  def bootstrap_status_class_for_interview_process status
    case status.to_s
    when "pending" then "bg-warning text-dark"
    when "canceled" then "bg-secondary"
    when "scheduled" then "bg-primary"
    when "completed" then "bg-success"
    when "rescheduled" then "bg-info"
    else "bg-light text-dark"
    end
  end

  def bootstrap_result_class result
    case result.to_s
    when "pass" then "bg-success"
    when "fail" then "bg-danger"
    when "waiting" then "bg-warning text-dark"
    else "bg-light text-dark"
    end
  end

  def stage_type_options
    InterviewProcess.stage_types.keys.map{|type| [type.humanize, type]}
  end

  def interview_type_options
    InterviewProcess.interview_types.keys.map{|type| [type.humanize, type]}
  end

  def application_status_options
    Application.statuses.keys.map{|s| [s.humanize, s]}
  end

  def interview_process_status_options
    InterviewProcess.statuses.keys.map{|s| [s.humanize, s]}
  end

  def interview_process_result_options
    InterviewProcess.results.keys.map{|s| [s.humanize, s]}
  end
end

app/helpers/enterprise/dashboard_helper.rb
module Enterprise::DashboardHelper
  def sort_options
    [
      [t("enterprise.scout.select_sorter"), ""],
      [t("enterprise.scout.name_asc"), "name"],
      [t("enterprise.scout.name_desc"), "name_desc"],
      [t("enterprise.scout.age_asc"), "age"],
      [t("enterprise.scout.age_desc"), "age_desc"]
    ]
  end

  def avatar_url_for user
    if user.avatar.attached?
      url_for(user.avatar)
    else
      "https://via.placeholder.com/80"
    end
  end
end

app/helpers/enterprise/job_helper.rb
module Enterprise::JobHelper
  def work_type_options
    Job.work_types.keys.map{|key| [key.humanize, key]}
  end

  def status_options
    Job.statuses.keys.map{|key| [key.humanize, key]}
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def work_types
    [
      {key: "jobs.filter.remote", value: "0"},
      {key: "jobs.filter.office", value: "1"},
      {key: "jobs.filter.hybrid", value: "2"},
      {key: "jobs.filter.overseas", value: "3"}
    ]
  end

  def locations
    [
      {key: "jobs.filter.hanoi", value: "Hà Nội"},
      {key: "jobs.filter.danang", value: "Đà Nẵng"},
      {key: "jobs.filter.hcm", value: "Hồ Chí Minh"},
      {key: "jobs.filter.others", value: "others"}
    ]
  end
end

app/views/enterprise/jobs/_form.html.erb
<%= form_with model: @job, url: form_url, local: true, method: method do |f| %>
  <div class="row g-3">
    <div class="col-md-6">
      <%= f.label :title, t("enterprise.recruitment.job_name"), class: "form-label" %>
      <%= f.text_field :title, class: "form-control", placeholder: "Enter job title", required: true %>
    </div>

    <div class="col-md-6">
      <%= f.label :location, t("enterprise.recruitment.location"), class: "form-label" %>
      <%= f.text_field :location, class: "form-control", placeholder: "Enter job location", required: true %>
    </div>

    <div class="col-md-12">
      <%= f.label :description, t("enterprise.recruitment.job_description"), class: "form-label" %>
      <%= f.text_area :description, class: "form-control", placeholder: "Enter job description", rows: 5, required: true %>
    </div>

    <div class="col-md-6">
      <%= f.label :experience_level, t("enterprise.recruitment.experience"), class: "form-label" %>
      <%= f.select :experience_level, ["Intern", "Junior", "Mid-Level", "Senior", "Lead"], { prompt: "Select experience level" }, class: "form-select" %>
    </div>

    <div class="col-md-6">
      <%= f.label :salary_range, t("enterprise.recruitment.salary"), class: "form-label" %>
      <%= f.text_field :salary_range, class: "form-control", placeholder: "e.g. $2000 - $4000" %>
    </div>

    <div class="col-md-6">
      <%= f.label :work_type, t("enterprise.recruitment.work_type"), class: "form-label" %>
      <%= f.select :work_type, work_type_options, { prompt: "Select work type" }, class: "form-select" %>
    </div>

    <div class="col-md-6">
      <%= f.label :status, t("enterprise.recruitment.status"), class: "form-label" %>
      <%= f.select :status, statuses_options, { prompt: "Select status" }, class: "form-select" %>
    </div>

    <div data-controller="job-skills" data-job-skills-target="container" class="mb-3">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h5><%= t "enterprise.recruitment.required_skills" %></h5>
        <button class="btn btn-primary" data-action="job-skills#addRow">
          <i class="fa-solid fa-plus-circle"></i>
          <span class="ms-1"><%= t "enterprise.modal.add" %></span>
        </button>
      </div>
      <% (@job.required_skills || []).each_with_index do |(key, value), index| %>
        <div class="skill-row d-flex mb-2">
          <%= text_field_tag "job[required_skills][][key]", key, class: "form-control me-2" %>
          <%= text_field_tag "job[required_skills][][value]", value, class: "form-control me-2" %>
          <button class="btn btn-danger" data-action="job-skills#removeRow">Remove</button>
        </div>
      <% end %>

      <template data-job-skills-target="template">
        <div class="skill-row d-flex mb-2">
          <input type="text" name="job[required_skills][][key]" placeholder="Skill Type" class="form-control me-2">
          <input type="text" name="job[required_skills][][value]" placeholder="Skill Name" class="form-control me-2">
          <button class="btn btn-danger" data-action="job-skills#removeRow"><%= t "enterprise.modal.remove" %></button>
        </div>
      </template>  
    </div>



    <div class="col-12 text-end">
      <%= f.submit t("enterprise.modal.save"), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/enterprise/jobs/_job.html.erb
<tr>
  <td><%= job.title %></td>
  <td><%= job.location %></td>
  <td><%= job.status.humanize %></td>
  <td><%= job.salary_range %></td>
  <td>
    <%= link_to enterprise_job_path(id: job.id), class: "btn btn-info btn-sm" do %>
      <i class="fa-solid fa-eye"></i>
    <% end %>
    <%= link_to edit_enterprise_job_path(id: job.id), class: "btn btn-warning btn-sm" do %>
      <i class="fa-solid fa-edit"></i>
    <% end %>
    <% unless job.deleted_at %>
      <%= link_to enterprise_job_path(id: job.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" do %>
        <i class="fa-solid fa-trash"></i>
      <% end %>
    <% end %>
  </td>
  <td>
    <% if job.deleted_at %>
      <span class="badge bg-danger"><%= t "enterprise.recruitment.deleted" %></span>
    <% end %>
  </td>
</tr>

app/views/enterprise/jobs/edit.html.erb
<div class="container mt-4">
  <div class="d-flex align-items-center">
    <%= link_to enterprise_jobs_path, class: "btn btn-secondary" do %>
      <i class="fa-solid fa-arrow-left"></i>
      <span><%= t "enterprise.modal.back" %></span>
    <% end %>
    <span class="ms-3 fs-2 fw-bold"><%= t "enterprise.recruitment.edit_job" %></span>
  </div>
  <%= render partial: "form", locals: {method: :patch, form_url: enterprise_job_path(id: @job.id)} %>
</div>

app/views/enterprise/jobs/index.html.erb
<% provide(:title, "Recruiments") %>
<div>
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h2><%= t "enterprise.recruitment.job_title" %></h2>
    <%= link_to new_enterprise_job_path, class: "btn btn-primary" do %>
      <i class="fa-solid fa-plus-circle"></i>
      <span class="ms-1"><%= t "enterprise.recruitment.add_job" %></span>
    <% end %>
  </div>

  <table class="table table-bordered table-striped">
    <thead class="table-dark">
      <tr>
        <th><%= t "enterprise.recruitment.title" %></th>
        <th><%= t "enterprise.recruitment.location" %></th>
        <th><%= t "enterprise.recruitment.status" %></th>
        <th><%= t "enterprise.recruitment.salary" %></th>
        <th><%= t "enterprise.recruitment.action" %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render @jobs %>
    </tbody>
  </table>
</div>

app/views/enterprise/jobs/new.html.erb
<div class="container mt-4">
  <div class="d-flex align-items-center">
    <%= link_to enterprise_jobs_path, class: "btn btn-secondary" do %>
      <i class="fa-solid fa-arrow-left"></i>
      <span><%= t "enterprise.modal.back" %></span>
    <% end %>
    <span class="ms-3 fs-2 fw-bold"><%= t "enterprise.recruitment.add_job" %></span>
  </div>
  <%= render partial: "form", locals: {method: :post, form_url: enterprise_jobs_path} %>
</div>

app/views/enterprise/jobs/show.html.erb
<div class="container mt-4">
  <div class="card shadow-sm">
    <div class="card-header d-flex justify-content-between bg-primary text-white">
      <div class="d-flex align-items-center">
        <h3 class="mb-0 me-2"><%= @job.title %></h3>
        <span class="badge bg-info fs-6"><%= @job.status.humanize %></span>
      </div>
      <%= link_to edit_enterprise_job_path(id: @job.id), class: "btn btn-primary me-2" do %>
        <i class="fa-solid fa-edit"></i>
      <% end %>
    </div>
    <div class="card-body">
    <div class="row mb-3">

    <div class="mb-3 col-md-12">
      <h5><%= t "enterprise.recruitment.job_description" %></h5>
      <p><%= simple_format(@job.description) %></p>
    </div>

    <div class="col-md-6">
        <p><strong><%= t "user.apply.location" %></strong> <%= @job.location %></p>
        </div>

        <div class="col-md-6">
          <p><strong><%= t "user.apply.experience" %></strong> <%= @job.experience_level.humanize %></p>
        </div>
        </div>
        
        <div class="row mb-3">
        <div class="col-md-6">
          <p><strong><%= t "user.apply.work_type" %></strong> <%= @job.work_type.humanize %></p>
        </div>

        <div class="col-md-6">
          <p><strong><%= t "user.apply.salary" %></strong> <%= @job.salary_range.present? ? @job.salary_range : "Not specified" %></p>
        </div>
      </div>

      <div class="mb-3">
        <h5><%= t "enterprise.recruitment.required_skills" %></h5>
        <% if @job.required_skills.present? %>
          <ul class>
            <% @job.required_skills.each do |key, value| %>
              <li>
                <strong><%= key.humanize %>:</strong>
                <span class="badge bg-primary"><%= value %></span>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p><%= t "enterprise.recruitment.no_skill" %></p>
        <% end %>
      </div>


    </div>

    <div class="card-footer d-flex justify-content-end">
      <%= link_to t("enterprise.modal.back"), enterprise_jobs_path, class: "btn btn-secondary me-2" %>
      <%= button_to t("enterprise.modal.delete"), enterprise_job_path(id: @job.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this job?" }, class: "btn btn-danger" %>
    </div>
  </div>
</div>